#include <iostream>
#include <vector>

#include "TacoLite.h"

// to be able ti string without not converting types to string
// Type in the TacoLite library
static char const * TypeName(Type const type)
{
    //printing over the own type
    switch(type)
    {
        // to prove dynamic type insertion in statements
        case Type::Integer: return "Integer";
        case Type::Blob: return "Blob";
        case Type::Float: return "Float";
        case Type::Null: return "Null";
        case Type::Text: return "Text";
    }
    // in case it fails
    assert(false);
    return "Invalid";
}

int main() {
    // Exaple using TACO LITE.

    std::cout << "Welcome to SQLite integration!" << std::endl;

    try {
        // creating a database entirely in memory
        Connection connection = Connection::Memory();

        // creating table
        // taking RowId autogenerated by sqlite as Id
        Execute(connection, "create table Users (Name text, Age integer, Weight real)");

        // inserting data
        Execute(connection, "insert into Users (Name, Age, Weight) values (?, ?, ?)", "Eduardo", 24, 70.43);
        std::cout << "Inserted item: " << connection.RowId() << "\n";
        Execute(connection, "insert into Users (Name, Age, Weight) values (?, ?, ?)", "Ana Belen", 22, 62.56);
        std::cout << "Inserted item: " << connection.RowId() << "\n";
        Execute(connection, "insert into Users (Name, Age, Weight) values (?, ?, ?)", "Juanisimo", 36, 89.43);
        std::cout << "Inserted item: " << connection.RowId() << "\n";
        Execute(connection, "insert into Users (Name, Age, Weight) values (?, ?, ?)", "Angelo", 27, 74.76);
        std::cout << "Inserted item: " << connection.RowId() << "\n";

        // showing data by iteating over a new query
        // RowId = sqlite autogenerated id
        for (Row row : Statement(connection, "select RowId, Name, Age, Weight from Users"))
        {
            std::cout << row.GetInt(0) << ", ";
            std::cout << row.GetString(1) << ", ";
            std::cout << row.GetFloat(2) << ", ";
            std::cout << row.GetFloat(3) << "\n";
        }

    } catch(Exception const & e)
    {
        // c_str: Returns a pointer to an array that contains a
        // null-terminated sequence of characters (i.e., a C-string) representing the current value of the string object.
        std::cout << "Error: " << e.Message.c_str() << " => " << e.Result;
    }
    std::cout << "\nGood bye! [CONNECTION CLOSED]" << std::endl;
    return 0;
}